spring:
  data:
    mongodb:
      uri: mongodb+srv://balajisn:balajisn@cluster0.lptb7cf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: Product
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.balaji.cqrs.post.cqrs.dto